baseurl = "/"
languageCode = "en-us"
theme = "sam"
title = "Call me Sam"
[params]
clickablephotos = "true"
dateform = "Mon Jan 02, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 EST"
description = "A new Hugo site."
favicon = "/sam.ico"
footertext = "© eopizarro.net, 2018"
galleryfolder = "images/"
homepage = "home"
primaryimage = "/tn.png"
pygmentscodefences = true
pygmentsstyle = "monokai"
twittercard = "summary_large_image"
[[params.mainmenu]]
link = "/posts"
text = "posts"
[[params.mainmenu]]
link = "/about"
text = "about"
